# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np

In [2]:
arr = np.linspace(0, 20, 28).reshape(4, 7)
arr

array([[ 0.        ,  0.74074074,  1.48148148,  2.22222222,  2.96296296,
         3.7037037 ,  4.44444444],
       [ 5.18518519,  5.92592593,  6.66666667,  7.40740741,  8.14814815,
         8.88888889,  9.62962963],
       [10.37037037, 11.11111111, 11.85185185, 12.59259259, 13.33333333,
        14.07407407, 14.81481481],
       [15.55555556, 16.2962963 , 17.03703704, 17.77777778, 18.51851852,
        19.25925926, 20.        ]])

In [3]:
arr = np.random.uniform(0, 20, (4, 7))
arr

array([[10.58958971, 13.46172196,  3.73373039, 17.34740422, 16.82623378,
         1.11339892, 11.20276179],
       [ 8.71572774, 19.16157643,  3.03389604,  0.87313726,  3.65632971,
        18.45724936,  1.93412817],
       [ 3.55899854,  8.08633496,  0.3905106 ,  7.68823679,  3.63914883,
        15.95145285,  8.49305847],
       [19.50483545,  8.41551871, 19.639174  ,  2.92021273, 18.00018921,
        12.84545492, 16.2542192 ]])

In [4]:
mx = np.max(arr)
mn = np.min(arr)
arr = (arr - mn)/(mx - mn)
mx, mn, arr

(19.639174000493412,
 0.3905106019148752,
 array([[0.52985908, 0.67907112, 0.17368581, 0.88093876, 0.85386309,
         0.03755525, 0.56171439],
        [0.43250884, 0.97518801, 0.13732826, 0.02507326, 0.16966472,
         0.93859705, 0.08019349],
        [0.16460821, 0.39981084, 0.        , 0.37912898, 0.16877215,
         0.80841677, 0.42094081],
        [0.99302089, 0.41691249, 1.        , 0.13142222, 0.91485202,
         0.64705502, 0.82414598]]))

Нормализация вида ax+b

In [5]:
mx = np.max(arr)
mn = np.min(arr)

a = 1/(mx-mn)
b = -a*mn
print(a, b)

nr_arr = a*arr+b
nr_arr

1.0 -0.0


array([[0.52985908, 0.67907112, 0.17368581, 0.88093876, 0.85386309,
        0.03755525, 0.56171439],
       [0.43250884, 0.97518801, 0.13732826, 0.02507326, 0.16966472,
        0.93859705, 0.08019349],
       [0.16460821, 0.39981084, 0.        , 0.37912898, 0.16877215,
        0.80841677, 0.42094081],
       [0.99302089, 0.41691249, 1.        , 0.13142222, 0.91485202,
        0.64705502, 0.82414598]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [6]:
rnd_arr = np.random.randint(0, 10, size=(8, 10))
sum_lines = np.sum(rnd_arr, axis=1)
i = np.where(sum_lines == min(sum_lines))

rnd_arr, sum_lines, min(sum_lines), i, rnd_arr[i]

(array([[9, 8, 5, 5, 7, 7, 6, 4, 1, 0],
        [6, 0, 3, 3, 2, 6, 4, 3, 4, 3],
        [8, 1, 6, 4, 0, 0, 3, 8, 8, 8],
        [9, 9, 7, 5, 6, 5, 4, 2, 8, 8],
        [9, 7, 4, 3, 9, 2, 5, 5, 9, 5],
        [0, 5, 3, 6, 9, 3, 2, 8, 1, 7],
        [2, 7, 7, 1, 8, 1, 2, 6, 1, 5],
        [3, 1, 9, 1, 0, 5, 1, 7, 4, 4]]),
 array([52, 34, 46, 63, 58, 44, 40, 35]),
 34,
 (array([1], dtype=int64),),
 array([[6, 0, 3, 3, 2, 6, 4, 3, 4, 3]]))

In [7]:
rnd_arr = np.random.randint(0, 10, size=(8, 10))
i = np.where(np.sum(rnd_arr, axis=1) == min(np.sum(rnd_arr, axis=1)))
rnd_arr, rnd_arr[i], i

(array([[0, 1, 0, 7, 3, 2, 3, 5, 8, 7],
        [7, 1, 8, 0, 3, 1, 7, 0, 9, 8],
        [4, 0, 9, 8, 0, 5, 6, 5, 9, 6],
        [5, 9, 6, 2, 0, 8, 1, 5, 7, 4],
        [9, 7, 8, 4, 8, 9, 4, 5, 2, 1],
        [6, 4, 6, 0, 9, 8, 8, 6, 7, 3],
        [0, 2, 8, 1, 0, 3, 3, 5, 7, 1],
        [5, 4, 2, 6, 9, 7, 9, 0, 4, 2]]),
 array([[0, 2, 8, 1, 0, 3, 3, 5, 7, 1]]),
 (array([6], dtype=int64),))

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [8]:
a = np.array([0, 0, 0, 13])
b = np.array([6, 4, 0, 2])
sum((a-b)**2)**0.5

13.152946437965905

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [9]:
A = np.matrix(
    [[-1, 2, 4], 
     [-3, 1, 2], 
     [-3, 0, 1]])

B = np.matrix(
    [[3, -1], 
     [2, 1]])

C = np.matrix(
    [[7, 21], 
     [11, 8], 
     [8, 4]])

x = np.linalg.inv(A)*(-C)*np.linalg.inv(B)
x

matrix([[ 1.00000000e+00,  1.11022302e-15],
        [-2.00000000e+00,  1.00000000e+00],
        [ 3.00000000e+00, -4.00000000e+00]])

In [10]:
-np.linalg.inv(A).dot(C).dot(np.linalg.inv(B))

matrix([[ 1.00000000e+00,  1.11022302e-15],
        [-2.00000000e+00,  1.00000000e+00],
        [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [11]:
data = np.loadtxt('files/minutes_n_ingredients.csv', dtype=np.int32, delimiter=',', skiprows=1)
data

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [12]:
for i in range(1, data.shape[1]):
    print(f'#{i}: min = {data[:, i].min()} max = {data[:, i].max()}, mean = {data[:, i].mean()}, median = {np.median(data[:, i])}')

#1: min = 0 max = 2147483647, mean = 21601.00169, median = 40.0
#2: min = 1 max = 39, mean = 9.05528, median = 9.0


In [13]:
data.shape

(100000, 3)

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [14]:
quantile_75 = np.quantile(data[:, 1], 0.75)
print(quantile_75)
data[:, 1] = np.where(data[:, 1] > quantile_75, quantile_75, data[:, 1])
data

65.0


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [15]:
print(np.count_nonzero(data[:, 1] == 0))
data[:, 1] = np.where(data[:, 1] != 0, data[:, 1], 1)
data

479


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [16]:
len(np.unique(data[:, 1:3])) # Искал разные ID, так как не понятно, что такое разные рецепты

65

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [17]:
len(np.unique(data[:, 2])), np.unique(data[:, 2])

(37,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39]))

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [18]:
short_cut = data[np.where(data[:, 2] <= 5)[0]]
short_cut, short_cut.shape

(array([[446597,     15,      5],
        [204134,      5,      3],
        [ 25623,      6,      4],
        ...,
        [ 52088,     60,      5],
        [128811,     15,      4],
        [370915,      5,      4]]),
 (17262, 3))

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [19]:
np.max(data[:, 2]/data[:, 1]), data[:, 2]/data[:, 1]

(24.0,
 array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
        0.21538462]))

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [20]:
sorted_indices = np.argsort(data[:, 1])[-100:]
sorted_array = data[sorted_indices]
sorted_array[:, 2].mean()

9.96

In [21]:
# Сортировка рецептов по продолжительности выполнения
sorted_data = data[data[:, 1].argsort()[::-1]]

# Выбор топ-100 рецептов с наибольшей продолжительностью
top_100_recipes = sorted_data[:100]

# Вычисление среднего количества ингредиентов для топ-100 рецептов
mean_ingredients_top_100 = np.mean(top_100_recipes[:, 2])

# Вывод результата
print("Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью:", mean_ingredients_top_100)

Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью: 9.96


In [22]:
sorted_data9 = data[data[:, 1].argsort()[::-1]]
top_100_recipes = sorted_data9[:100]
avg_ingredients = np.average(top_100_recipes[:, 2])
print("Среднее количество ингредиентов для топ-100 рецептов:", avg_ingredients)

Среднее количество ингредиентов для топ-100 рецептов: 9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [23]:
idx = np.random.randint(data.shape[0], size=10)
data[idx, :]

array([[192000,     40,     15],
       [210730,     55,      9],
       [512488,     45,     12],
       [172926,     65,     13],
       [384584,     40,      5],
       [124985,     15,      5],
       [262473,     10,      5],
       [311653,     35,     12],
       [202551,     20,      4],
       [215181,      5,      9]])

In [24]:
random_indices = np.random.choice(len(data), size=10, replace=False)

random_recipes = data[random_indices]

print("Информация о случайно выбранных рецептах:")
print(random_recipes)

Информация о случайно выбранных рецептах:
[[281838     10     11]
 [ 37736     10      5]
 [237302     15      4]
 [214633     55      8]
 [211253     10      5]
 [456235     20      6]
 [ 47450     27      8]
 [ 30898     65     14]
 [194910     40     14]
 [ 49243     60      8]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [25]:
str(len(np.where(data[:, 2] < data[:, 2].mean())[0])/data.shape[0]*100) + "%"

'58.802%'

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [30]:
good_recepts = np.zeros((data.shape[0], 4), dtype=int) # Создаём пустой датасет
good_recepts[:, :3] = data # Заполняем первые 3
good_recepts[np.where((data[:, 2] <= 5) & (data[:, 1] <= 20)), 3] = 1
good_recepts

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [27]:
str(sum(good_recepts[:, 3])/data.shape[0]*100) + '%'

'9.552%'

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [28]:
short_recipes = data[data[:, 1] < 10]
standard_recipes = data[(data[:, 1] >= 10) & (data[:, 1] < 20)]
long_recipes = data[data[:, 1] >= 20]

max_length = min(len(short_recipes), len(standard_recipes), len(long_recipes))

three_dimensional_array = np.zeros((3, max_length, 3), dtype=int)

three_dimensional_array[0, :max_length, :] = short_recipes[:max_length]
three_dimensional_array[1, :max_length, :] = standard_recipes[:max_length]
three_dimensional_array[2, :max_length, :] = long_recipes[:max_length]

three_dimensional_array.shape, three_dimensional_array

((3, 7588, 3),
 array([[[ 67660,      5,      6],
         [366174,      7,      9],
         [204134,      5,      3],
         ...,
         [420725,      5,      3],
         [  4747,      1,      9],
         [370915,      5,      4]],
 
        [[ 94746,     10,      6],
         [ 33941,     18,      9],
         [446597,     15,      5],
         ...,
         [  9831,     15,      7],
         [335859,     12,     14],
         [256812,     10,      3]],
 
        [[127244,     60,     16],
         [ 23891,     25,      7],
         [157911,     60,     14],
         ...,
         [168901,     25,      7],
         [392339,     35,     13],
         [206732,     45,     10]]]))